import type { Branch } from '@/types/domain'

// Branch managers are resolved from each branch's employees at seed time (see mock-data/index.ts).
export const branches: Branch[] = [
  {
    id: 'br_fl_head',
    companyId: 'co_frontline',
    name: 'Head Office – Makati',
    isHeadOffice: true,
    code: 'FL-MKT-HO',
    address: '12th Floor, Ayala Tower One, Ayala Avenue, Bel-Air',
    city: 'Makati City, Metro Manila',
    contactNumber: '(02) 8812 4400',
    email: 'makati@frontlinebusiness.com.ph',
    openedDate: '2015-03-02',
  },
  {
    id: 'br_fl_qc',
    companyId: 'co_frontline',
    name: 'Quezon City Branch',
    isHeadOffice: false,
    code: 'FL-QC-01',
    address: '3F Eton Centris, EDSA cor. Quezon Avenue, Pinyahan',
    city: 'Quezon City, Metro Manila',
    contactNumber: '(02) 8921 3350',
    email: 'qc@frontlinebusiness.com.ph',
    openedDate: '2018-07-16',
  },
  {
    id: 'br_fl_davao',
    companyId: 'co_frontline',
    name: 'Davao Branch',
    isHeadOffice: false,
    code: 'FL-DVO-01',
    address: 'Unit 504, Abreeza Corporate Center, J.P. Laurel Avenue, Bajada',
    city: 'Davao City, Davao del Sur',
    contactNumber: '(082) 285 7710',
    email: 'davao@frontlinebusiness.com.ph',
    openedDate: '2021-02-01',
  },

  {
    id: 'br_mb_head',
    companyId: 'co_manila_bay',
    name: 'Head Office – Pasay',
    isHeadOffice: true,
    code: 'MB-PSY-HO',
    address: 'Seaside Boulevard, Mall of Asia Complex',
    city: 'Pasay City, Metro Manila',
    contactNumber: '(02) 8556 1200',
    email: 'pasay@manilabay.com.ph',
    openedDate: '2012-09-10',
  },
  {
    id: 'br_mb_cavite',
    companyId: 'co_manila_bay',
    name: 'Cavite Warehouse',
    isHeadOffice: false,
    code: 'MB-CAV-WH',
    address: 'Lot 7, Gateway Business Park, Javalera',
    city: 'General Trias, Cavite',
    contactNumber: '(046) 433 2081',
    email: 'cavite@manilabay.com.ph',
    openedDate: '2019-05-20',
  },

  {
    id: 'br_cc_head',
    companyId: 'co_cebu_craft',
    name: 'Head Office – Cebu City',
    isHeadOffice: true,
    code: 'CC-CEB-HO',
    address: 'Cebu IT Park, Salinas Drive, Lahug',
    city: 'Cebu City, Cebu',
    contactNumber: '(032) 231 5500',
    email: 'cebu@cebucraft.ph',
    openedDate: '2014-01-13',
  },
  {
    id: 'br_cc_mandaue',
    companyId: 'co_cebu_craft',
    name: 'Mandaue Plant',
    isHeadOffice: false,
    code: 'CC-MND-PL',
    address: 'M.C. Briones Street, Tipolo',
    city: 'Mandaue City, Cebu',
    contactNumber: '(032) 346 8120',
    email: 'mandaue@cebucraft.ph',
    openedDate: '2017-11-06',
  },
]
