import type { Company } from '@/types/domain'

export const companies: Company[] = [
  {
    id: 'co_frontline',
    name: 'Frontline Business Solutions',
    tradeName: 'FBS OPS',
    planTier: 'professional',
    billingInterval: 'monthly',
    nextRenewalDate: '2026-10-15',
    timezone: 'Asia/Manila',
    payrollFrequency: 'semi_monthly',
    createdAt: '2022-01-10T00:00:00.000Z',
    companyType: 'corporation',
    industry: 'Business Process Outsourcing',
    description: 'Payroll, HR, and back-office support services for Philippine SMEs and BPO clients.',
    website: 'https://www.frontlinebusiness.com.ph',
    email: 'contact@frontlinebusiness.com.ph',
    contactNumber: '+63 2 8123 4567',
    registration: {
      secNo: 'CS202201234',
      birTin: '123-456-789-000',
      rdoCode: 'RDO 047 - East Makati',
      philhealthEmployerNo: '13-000123456-7',
      sssEmployerNo: '03-9876543-2',
      pagibigEmployerNo: '1234-5678-9012',
      businessPermitNo: 'MKT-2024-0098765',
    },
    registeredAddress: {
      buildingUnit: '12th Floor, Ayala Tower One',
      street: 'Ayala Avenue',
      barangay: 'Bel-Air',
      city: 'Makati City',
      province: 'Metro Manila',
      region: 'NCR',
      zipCode: '1226',
      country: 'Philippines',
    },
    sameAsRegisteredAddress: true,
    primaryContact: {
      name: 'Thea Consignado',
      position: 'HR & Admin Director',
      email: 'contact@frontlinebusiness.com.ph',
      contactNumber: '+63 917 123 4567',
    },
    payrollContact: {
      name: 'Marites Lagman',
      email: 'payroll@frontlinebusiness.com.ph',
      contactNumber: '+63 917 234 5678',
    },
    hrContact: {
      name: 'Rafael Bautista',
      email: 'hr@frontlinebusiness.com.ph',
      contactNumber: '+63 917 345 6789',
    },
  },
  {
    id: 'co_manila_bay',
    name: 'Manila Bay Logistics',
    planTier: 'standard',
    billingInterval: 'monthly',
    nextRenewalDate: '2026-10-02',
    timezone: 'Asia/Manila',
    payrollFrequency: 'monthly',
    createdAt: '2023-04-02T00:00:00.000Z',
  },
  {
    id: 'co_cebu_craft',
    name: 'Cebu Craft Foods',
    planTier: 'basic',
    billingInterval: 'monthly',
    nextRenewalDate: '2026-10-18',
    timezone: 'Asia/Manila',
    payrollFrequency: 'semi_monthly',
    createdAt: '2024-02-18T00:00:00.000Z',
  },
]
