import type { SessionUser } from '@/types/domain'

export const users: SessionUser[] = [
  {
    id: 'u_fl_admin',
    companyId: 'co_frontline',
    role: 'company_admin',
    name: 'Andrea Villareal',
    email: 'andrea.villareal@frontlinebusiness.com.ph',
    isActive: true,
  },
  {
    id: 'u_fl_hr',
    companyId: 'co_frontline',
    role: 'hr_admin',
    name: 'Patrick Ong',
    email: 'patrick.ong@frontlinebusiness.com.ph',
    isActive: true,
  },
  {
    id: 'u_fl_payroll',
    companyId: 'co_frontline',
    role: 'payroll_admin',
    name: 'Karen Sison',
    email: 'karen.sison@frontlinebusiness.com.ph',
    isActive: true,
  },
  {
    id: 'u_fl_manager',
    companyId: 'co_frontline',
    branchId: 'br_fl_qc',
    role: 'manager',
    name: 'Ramon Torres',
    email: 'ramon.torres@frontlinebusiness.com.ph',
    employeeId: 'co_frontline_emp_0005',
    isActive: true,
  },
  {
    id: 'u_fl_employee',
    companyId: 'co_frontline',
    branchId: 'br_fl_qc',
    role: 'employee',
    name: 'Maria Santos',
    email: 'maria.santos@frontlinebusiness.com.ph',
    employeeId: 'co_frontline_emp_0001',
    isActive: true,
  },
  {
    id: 'u_fl_hr2',
    companyId: 'co_frontline',
    role: 'hr_admin',
    name: 'Grace Ocampo',
    email: 'grace.ocampo@frontlinebusiness.com.ph',
    isActive: false,
  },
  {
    id: 'u_mb_admin',
    companyId: 'co_manila_bay',
    role: 'company_admin',
    name: 'Ferdinand Cruz',
    email: 'ferdinand.cruz@manilabaylogistics.ph',
    isActive: true,
  },
  {
    id: 'u_super_admin',
    companyId: 'co_frontline',
    role: 'super_admin',
    name: 'FBS Platform Admin',
    email: 'platform@frontlinebusiness.com.ph',
    isActive: true,
  },
]
